sudo: required
language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
before_script:
  - 'wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz'
  - 'tar xvfJ ffmpeg-release-64bit-static.tar.xz'
  - 'cd ffmpeg*'
  - 'sudo cp ffmpeg /bin'
  - 'cd ..'
before_install: npm install -g grunt-cli
install: npm install