language: node_js
os: linux
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - ffmpeg
before_install:
  - ffmpeg -version
  - npm install -g grunt-cli
install: npm install